# Generated by Django 4.0.5 on 2022-06-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0002_user_verified_alter_user_google_id_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.CharField(max_length=255)),
                ('user_argent', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
