# Generated by Django 4.0.5 on 2022-06-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0003_session_alter_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='google_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
