# Generated by Django 4.0.5 on 2022-06-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0004_session_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='google_id',
            field=models.EmailField(max_length=254),
        ),
    ]
