# Generated by Django 4.0.5 on 2022-06-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0005_alter_session_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creation_date',
            field=models.DateTimeField(default=(2022, 6, 28, 18, 53, 29, 1, 179, 0)),
        ),
    ]
