# Generated by Django 4.0.5 on 2022-06-28 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0006_alter_session_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 18, 57, 25, 608717)),
        ),
    ]
