# Generated by Django 4.0.5 on 2022-06-28 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0009_alter_session_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
