# Generated by Django 4.0.5 on 2022-06-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0010_alter_session_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user_argent',
            new_name='user_agent',
        ),
    ]
