# Generated by Django 4.0.5 on 2022-06-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0011_rename_user_argent_session_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
