# Generated by Django 4.0.5 on 2022-06-29 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0012_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_google_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2500)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receivers_google_ids', models.CharField(max_length=600)),
            ],
        ),
    ]
