# Generated by Django 4.0.5 on 2022-07-04 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_id', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('monitors_google_id', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
