# Generated by Django 4.0.5 on 2022-07-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0014_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='monitors_google_id',
            field=models.CharField(max_length=6000),
        ),
    ]
