# Generated by Django 4.0.5 on 2022-07-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leontools_backend', '0015_alter_request_monitors_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='generated_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
